---
date: 2022-08-14
last_modified_at시: 2022-08-14
categories: JAVA
tags:
  - java
  - 자바의정석
  - 예외
---
### 프로그램 오류

```java
system.out.println(args[0]); //컴파일 에러
System.out.println(args[0]); //런타임 에러 : 실행중 발생하는 에러. 매개변수로 받은 값이 없는데 실행해서 생김
```

- 논리적에러(logical error) : 작성 의도와 다르게 동작
- 컴파일러에러(compile-time error) : 컴파일 할 때 발생하는 에러번호
    - 컴파일러
        1. 구문체크
        2. 번역
        3. 최적화 (ex. int i = 3+5를 8로 변경)
- 런타임에러(runtime error) : 실행할 때 발생하는 에러. 프로그램종료
    - 에러 (error) : 프로그램코드에 의해 수습될 수 없는 심각한 오류  
        ex)Out Of Memory Error - OOME : 메모리부족으로 일어나는 오류  
        
    - 예외 (exception) : 프로그램코드에 의해 수습될 수 있는 다소 미약한 오류  
        ex)RuntimeException, IOException  
        
        - Excepton클래스들 : 사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외
            
            — checked예외 : 컴파일러가 예외처리 여부를 체크(예외처리 필수)
            
        - RuntimeException 클래스들 : 프로그래머의 실수로 발생하는 예외
            
            — unchecked예외 : 컴파일러가 예외처리 여부를 체크 안함.(예외처리 선택)   
		```java
            throw new Exception("고의로 발생");  //try-catch문이 없어 컴파일 조차 안됨
            		throw new RuntimeException("고의로 발생");  //try-catch가 없어도 컴파일은 됐으나 실행중 에러. 비정상 종료
		```

		- 예외처리(exception handling) : 프로그램 실행시 발생할 수 있는 예외의 발생에 대비한 코드를 작성.  
            프로그램의 비정상 종료를 막고 정상적인 실행상태를 유지  
            — try - catch문 사용 - {}생략불가.  
            
            try { /*예외가 발생할 가능성이 있는 문장을 넣는다*/  
            } catch (Exception1 e1) { /* Exception1이 발생했을 경우, 이를 처리하기 위한 문장을 넣음*/  
            } catch (Exception2 e2) { /* Exception2이 발생했을 경우, 이를 처리하기 위한 문장을 넣음*/  
            catch (ExceptionN eN) { /* ExceptionN이 발생했을 경우, 이를 처리하기 위한 문장을 넣음*/  
            
            - try블럭에서 예외가 발생한 경우
                1. 발생한 예외와 일치하는 catch블럭이 있는지 확인
                2. 일치하는 catch블럭을 찾게 되면, 그 catch블럭 내의 문장들을 수행하고 전체 try-catch문을 빠져나가서 그 다음문장을 계속해서 수행한다. 만일 일치하는 catch블럭을 찾지 못하면, 예외는 처리되지 못한다.
            - try블럭 내에서 예외가 발생하지 않은 경우
                
                1. catch블럭을 거치지 않고 전체 try-catch문을 빠져나가 수행을 계속한다.
                
				```java
                public class ex {
                	public static void main(String[] args) {
                		System.out.println(1);
                		try {
                			System.out.println(2);
                			System.out.println(3);
                		} catch (Exception e) {
                			System.out.println(4); //예외가 발생하지 않아서 출력안됨. 
                		}//try-catch문의 끝
                		System.out.println(5);  //1 2 3 5 출력됨
                		System.out.println("=============");
                		System.out.println(1);
                		try {
                			System.out.println(0/0); //예외 발생 0으로 나누기 금지
                			System.out.println(2);
                		} catch (ArithmeticException e) {
                			System.out.println(3);
                		}//try-catch문의 끝
                		System.out.println(4);  //1 3 4 출력됨
                	}//main 메소드의 끝
                }
```
                
        - printStackTrace() : 예외발생 당시의 호출스택(Call strack)에 있었던 메소드의 정보와 예외 메시지를 화면에 출력한다.
        - getMessage() : 발생한 예외클래스의 인스턴스에 저장된 메세지를 얻을 수 있다.
        
			```java
        public class ex {
        	public static void main(String[] args) {
        		System.out.println(1);
        		System.out.println(2);
        		try {
        			System.out.println(3);
        			System.out.println(0/0); //ArithmeticException예외 발생 0으로 나누기 금지
        			System.out.println(4); //실행안됨
        		} catch (ArithmeticException ae) {
        			ae.printStackTrace();
        			System.out.println("예외 메세지 : "+ae.getMessage()); 
        		} catch (Exception e) {  //Exception : 모든 예외의 최고조상, 모든 예외를 처리함(맨 마지막에 와야함)
        			System.out.println("Exception"); //실행안됨
        		}//try-catch문의 끝
        		System.out.println(6);  
        		//1 2 3   java.lang.ArithmeticException: / by   zero 예외 메세지 : / by zero   6 출력됨
        	}//main 메소드의 끝
        }
```
        
        - 예외 발생시키기
            1. 연산자 new를 이용해 발생시키려는 예외 클래스의 객체를 만든다  
                Exception e = new Exception(”고의로 발생시켰음”);  
                
            2. 키워드 throw를 이용해 예외 발생  
                throw e;  
                
        - 예외 처리방법
            - 멀티 catch블럭(try - catch문) : 내용이 같은 catch블럭을 하나로 합친 것 (JDK1.7부터)  
                try { /*…*/ } catch (ExceptionA | ExceptionB) { e.printStackTrace (); }  
                
                멀티catch블록에 쓰는 두 클래스가 부모자식관계면 에러. 부모만써도 같은 의미라서 에러표시됨
                
				```java
                public class ex {
                	public static void main(String[] args) {
                		System.out.println(1);
                		System.out.println(2);
                		try {
                			System.out.println(3);
                			System.out.println(0/0); //ArithmeticException예외 발생 0으로 나누기 금지
                			System.out.println(4); //실행안됨
                		} catch (ExceptionA | ExceptionB e) {  //Exception : 모든 예외의 최고조상, 모든 예외를 처리함(맨 마지막에 와야함)
                //			e.methodA(); //에러, e에 ExceptionA가 들어올지 ExceptionB가 들어올지 알수 없음. methodA는 ExceptionA의 멤버라서 에러
                			//ExceptionA,ExceptionB의 공통멤버는 사용 가능
                			if(e instanceof ExceptionA) {
                				ExceptionA e1 = (ExceptionA)e;
                				e1.methodA();
                			}
                			else {
                				ExceptionB e2 = (ExceptionB)e;
                				e2.methodB();
                			}
                		}//try-catch문의 끝
                		System.out.println(6);  
                	}//main 메소드의 끝
                }
```
                
            - 메소드에 예외 선언하기 : 빈catch블럭을 사용함
                
                ❗예외를 발생시키는 키워드 throw와 메소드에 선언할 때 쓰이는 throws를 잘 구분 할 것.
                
				```java
                static void startInstall() throws SpaceException, MemoryException{
                	if(!enoughSpace()) //설치공간이 부족하다면
                		throw new SpaceException("설치공간 부족");
                	if(!enoughMemory()) //메모리가 부족하다면
                		throw new MemoryException("메모리 부족");
                } //내가 처리할 수 없는 것들. 사용자에게 해결하고 오라고 떠넘김
```
                
				```java
                public class ex {
                	public static void main(String[] args) throws Exception{
                	method1(); //같은 클래스 내의 static멤버이므로 객체생성없이 직접 호출 가능
                	}
                	static void method1()throws Exception {
                		method2();
                	}
                	static void method2() throws Exception{
                		throw new Exception();
                	}
                } //method2에서 발생한 Exception이 try-catch문을 만나지 못해 method1-main까지 올라갔다가 JVM까지 올라감 -> 비정상종료
                //try-catch문이 하나는 있어야 해결이됨.
```
                
				```java
                import java.io.*;
                
                public class ex {
                	public static void main(String[] args) {
                			File f = createFile("");
                			System.out.println(f.getName()+" 파일이 성공적으로 생성되었습니다");
                		}
                
                 static File createFile(String fileName){
                	try {
                		if(fileName == null || fileName.equals(""))
                	 {
                		 throw new Exception("파일 이름이 유효하지 않습니다.");
                	 }
                	} catch(Exception e) {
                		 fileName = "제목없음.txt";
                	 }
                	 File f = new File(fileName); //File클래스의 객체 생성
                	 try {
                		f.createNewFile();
                	} catch (IOException e) {
                		e.printStackTrace();
                	}finally{
                		//예외 발생 여부와 상관없이 무조건 실행해야함. 코드 중복 박기 위해
                	}
                	 return f;
                	}
                 }
```
                
            - finally블럭 : 예외 발생 여부와 관계없이 수행되어야 하는 코드
                
                ⚠️ try블럭안에 return문이 있어서 try블럭을 벗어나갈 때도 finally블럭이 실행 됨
                
        - 사용자정의 예외 만들기
            
            : 우리가 직접 예외 클래스를 정의할 수 있다.
            
            조상은 Exception과 RuntimeException중에 선택 (웬만하면 RuntimeException으로 할것. try-catch문 꼭 안써줘도 됨)
            
			```java
            class MyException extends Exception{
            	MyException(String msg){ //문자열을 매개변수로 받는 생성자
            		super(msg); //조상인 Exception의 생성자를 호출
            	}
            }
```
            
			```java
            class MyException extends Exception{
            	//에러코드 값을 저장하기 위한 필드 추가
            	private final int ERR_CODE;
            	 MyException(String msg, int errCode){ //생성자
            		 super(msg);
            		 ERR_CODE = errCode;
            	 }
            	 MyException(String msg){ //생성자
            		 this(msg, 100); //ERR_CODE를 100(기본값)으로 초기화
            	 }
            	 public int getErrCode() { //에러코드를 얻을 수 있는 메소드도 추가
            		 return ERR_CODE; //주로 getMessage()와 함께 사용될 것.
            	 }
            	}
```
            
        - 예외 되던지기(exception re-throwing)
            
            : 예외를 처리한 후에 다시 예외를 발생시킴
            
			```java
            public class Main {
            	public static void main(String[] args) {
            		try {
            			method1();
            		} catch (Exception e) {
            			System.out.println("main메소드에서 예외처리 되었습니다");
            		} //예외 2번처리 = 예외 되던지기 = 예외 양쪽에서 처리
            	}
            static void method1() throws Exception{
            		try {
            			throw new Exception();
            		}catch (Exception e) {
            			System.out.println("method1에서 예외가 처리되었습니다");
            			throw e;
            		}
            	}
            }
```
            
        - 연결된 예외(chained exception)
            
            : 한 예외가 다른 예외를 발생시킬 수 있다.
            
            예외 A가 예외 B를 발생시키면 A는 B의 원인예외(cause exception)
            
            Throwable initCause(Throwable cause) : 지정된 예외를 원인 예외로 등록
            
            Throwable getCause() : 원인 예외를 반환
            
			```java
            public class Throwable implements Serializable{
            	//...
            	private Throwable cause = this; //객체 자신(this)을 원인 예외로 등록
            	//...
            	public synchronized Throwable initCause(Throwable cause) {
            		//...
            		this.cause = cause; //cause를 원인 예외로 등록
            		return this;
            	}
            }
```
            
			```java
            void install() throws InstallException{ //실제로는 SpaceException이 발생했으나 InstallException안에 포함시켜서 예외 처리됨
            	try {
            		startInstall(); //SpaceException 발생, 저장공간 부족
            		copyFiles();
            	} catch (SpaceException e) {
            		InstallException ie = new InstallException("설치 중 예외 발행");
            		ie.initCause(e); //ie(InstallException)의 원인 예외를 e(SpaceException)으로 지정
            		throw ie; //InstallException 발생
            	}catch (MemoryException me) {
            		//......
            	} 
            }
```
            
            — 이유 1 : 여러 예외를 하나로 묶어서 다루기 위해
            
			```java
            void install() throws InstallException{ //실제로는 SpaceException이 발생했으나 InstallException안에 포함시켜서 예외 처리됨
            	try {
            		startInstall(); //SpaceException 발생, 저장공간 부족
            		copyFiles();
            	} catch (SpaceException e) {
            		InstallException ie = new InstallException("설치 중 예외 발행");
            		ie.initCause(e); //ie(InstallException)의 원인 예외를 e(SpaceException)으로 지정
            		throw ie; //InstallException 발생
            	}catch (MemoryException me) {
            		//......
            	} 
            }
            public class Main {
            
            	public static void main(String[] args) {
            //		try {
            //			install();
            //		} catch (SpaceException e) {
            //			e.printStackTrace();
            //		} catch (MemoryException e) {
            //			e.printStackTrace();
            //		} catch (Exception e) {
            //			e.printStackTrace();
            		try {
            			install();
            		} catch (InstallException e) {
            			e.printStackTrace();
            		} catch (Exception e) {
            			e.printStackTrace();
            		}
            	}
            }
```
            
            — 이유 2 : checked예외를 unchecked예외로 변경할때
            
			```java
            static void startInstall() throws SpaceException, MemoryException{
            	if(!enoughSpace())
            		throw new SpaceException("설치할 공간이 부족합니다.");
            	if(!enoughMemory())
            		throw new RuntimeException(new MemoryException("메모리가 부족합니다."));		
            }//MemoryException을 RuntimeException으로 위장해 try-catch문은 사용하지않아도됨
            //class SpaceException extends Exception{
            //	SpaceException(String msg){
            //		super(msg);
            	}
            }
```